### ISSUE TITLE
[MRC Documentation] Generate book via automated cargo docs for MRC

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/mrc#84]
**Tasks:**

Cargo enables generating book out of comments with specific format i.e. /// . For MRC
- [x] Setup scripts to generate book via cargo docs 
- [x] Setup workflow to generate mrc book
- [ ] Update Readme with information on how to write document-able comments 

Acceptance Criteria:
- [x] Scripts be able to generate only MRC related cargo book and removing substrate docs in between
- [x] MRC rust docs should only contain information on MRC related pallets

**Comment by saraswatpuneet** [comment]
https://doc.rust-lang.org/rust-by-example/meta/doc.html

**Comment by saraswatpuneet** [comment]
https://doc.rust-lang.org/cargo/commands/cargo-rustdoc.html

https://stackoverflow.com/questions/70673143/difference-between-cargo-doc-and-cargo-rustdoc

We have to ensure we only document MRC crates, check difference between cargo doc vs cargo rustdoc
